AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdards:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambdadynamodb
      Description: 'Lambda function connecting dynamodb'
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Runtime: python3.7
      Tracing: Active
      Timeout: 10
