---
- name: deploy the hpdc lab
  hosts: localhost
  tasks:
  - route53_zone:
      zone: "{{name}}.retailplay.co"
      state: present
      comment: Lab exercise
    register: route53out
  - debug:
      var: route53out
  - community.aws.route53:
      command: get
      zone: "{{name}}.retailplay.co"
      record: "{{name}}.retailplay.co"
      type: NS
    register: rec
  - debug:
      var: rec
  - name: Update new.foo.com as an A record with a list of 3 IPs and wait until the changes have been replicated
    community.aws.route53:
      aws_access_key: "{{accesskey}}"
      aws_secret_key: "{{secretkey}}"
      state: present
      zone: retailplay.co
      record: "{{name}}.retailplay.co"
      type: NS
      ttl: 7200
      value: "{{rec.nameservers}}"
      wait: yes
      
