---
- name: deploy the hpdc lab
  hosts: localhost
  tasks:
  - name: launch a vpc
    cloudformation:
      stack_name: "vpc"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "vpc.yaml"
    register: vpcout
  - name: example ec2 key
    ec2_key:
      region: "us-east-1"
      name: ecommkey
    register: ecommkeyout
  - name: example copying file with owner and permissions
    copy:
      content: "{{ecommkeyout.key.private_key}}"
      dest: ecomm.pem
      mode: 0600
    when: ecommkeyout is changed
  - name: launch a db instance
    cloudformation:
      stack_name: "hddcdb"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "dbinstance.yaml"
      template_parameters:
         VPCID: "{{vpcout.stack_outputs.VPCID}}"
         Subnet1: "{{vpcout.stack_outputs.PrivateSubnet1ID}}"
         Subnet2: "{{vpcout.stack_outputs.PrivateSubnet2ID}}"
    register: dbinstance
  - name: launch a amiinstance
    cloudformation:
      stack_name: "amiinstance"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "amiinstance.yaml"
      template_parameters:
         VPCID: "{{vpcout.stack_outputs.VPCID}}"
         SubnetId: "{{vpcout.stack_outputs.PublicSubnet1ID}}"
    register: amiinstanceout
  - name: add the hosts
    add_host: 
      name: '{{amiinstanceout.stack_outputs.EC2PublicIp}}'
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ecomm.pem
      ansible_become: yes
  - import_tasks: installwordpress.yaml
    delegate_to: '{{amiinstanceout.stack_outputs.EC2PublicIp}}'
  - copy:
      content: |
        vpcid: "{{vpcout.stack_outputs.VPCID}}"
        publicsn1: "{{vpcout.stack_outputs.PublicSubnet1ID}}"
        publicsn2: "{{vpcout.stack_outputs.PublicSubnet2ID}}"
        privatesn1: "{{vpcout.stack_outputs.PrivateSubnet1ID}}"
        privatesn2: "{{vpcout.stack_outputs.PrivateSubnet2ID}}"
        instanceid: '{{amiinstanceout.stack_outputs.EC2InstanceId}}'
      dest: amiserverout.yaml
     