---
- name: deploy the hpdc lab
  hosts: localhost
  tasks:
  - name: Deploy Autoscaling and ALb
    cloudformation:
      stack_name: "autoscaling"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "autoscaling.yaml"
      template_parameters:
        VPCID: "{{vpcid}}"
        PrivateSubnet1ID: "{{privatesn1}}"
        PrivateSubnet2ID: "{{privatesn2}}"
        KeyName: ecommkey
        Ami: "ami-0543b5911f8fcb664"
        targetgroup: "{{targetgroup}}"
        instancesg: "{{instancesg}}"
         
  
